---
title: "EFA_ExampleCode_Wishkerman"
author: "Soren Pedersen"
date: "06/12/2021"
output: html_document
---
#From https://github.com/wishkerman/DiaOutline 

# Install package
```{r, echo=TRUE}
install.packages("Momocs")

# Load package
library(Momocs)
```

##### Outline analysis - Species data
```{r, echo=TRUE}
lf <- list.files("E:/DiaOutlineDataset/", pattern = "\\.txt$",full.names=TRUE)  
lf1<-lf_structure(lf,  split = "E:/DiaOutlineDataset/", trim.extension = FALSE)
lf2<-data.frame(substr(lf1$V2, 1, 5))
names(lf2)[1] <- "Type"

coordinates <- import_txt(lf) 
allDiatomOutlines<-Out(coordinates, fac = lf2)

panel(allDiatomOutlines, fac="Type", names=TRUE)
# stack(allDiatomOutlines)
stack(coo_center(allDiatomOutlines))
calibrate_harmonicpower(allDiatomOutlines) #Estimates the number of harmonics required for the four Fourier methods implemented in Momocs
allDiatomOutlines.f <- efourier(allDiatomOutlines, nb.h=32) #Num. of harmonics set to 32
```

### PCA: Principal Component Analysis
```{r, echo=TRUE}
allDiatomOutlines.p <- PCA(allDiatomOutlines.f)

tiff("E:/Supplement_10AllPCA.tiff", height = 12, width = 17, units = 'cm', compression = "lzw", res = 500)
plot(allDiatomOutlines.p, 1, chull.filled=TRUE,stars=TRUE, title="All data PCA") #Supplement 10 in the paper.
dev.off()

plot(allDiatomOutlines.p,"Type", title="All data PCA")
plot(allDiatomOutlines.p, 1, chull=TRUE, pos.shp = "full_axes", abbreviate.labelsgroups = TRUE, points=FALSE, labelspoints = TRUE)
```

### Linear Discriminant Analysis
```{r, echo=TRUE}
allDiatomOutlines.l <- LDA(allDiatomOutlines.p,1)

tiff("E:/Fig8AllLDA.tiff", height = 12, width = 17, units = 'cm', compression = "lzw", res = 500)
plot(allDiatomOutlines.l, chull.filled=TRUE, stars=TRUE, title="All data LDA") #Fig 8 in the paper.
dev.off()

plot(allDiatomOutlines.l, title="All data LDA") #Another plot version
plot(allDiatomOutlines.l, 1, chull=TRUE, pos.shp = "full_axes", abbreviate.labelsgroups = TRUE, points=FALSE, labelspoints = TRUE) #Another plot version
```

##### MANOVA
```{r, echo=TRUE}
m<-MANOVA(allDiatomOutlines.p, 'Type')
mpw<-MANOVA_PW(allDiatomOutlines.p, "Type")

sink("E:/Manova.txt")
lapply(mpw, print)
sink() 
```
